github.com:
    user: apetl
    git_protocol: https
    users:
        petlikarayan:
            oauth_token: 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
        apetl:
            oauth_token: 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
    oauth_token: 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
